# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# MAVEN TASK
- task: Maven@3
  inputs:
    mavenPomFile: 'online-bookstore-app/pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '21'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- script: |
    ls -R $(Build.SourcesDirectory)/online-bookstore-app/target
  displayName: 'List directory contents'

# PUBLISH ARTIFACT STEP
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/online-bookstore-app/target'
    artifact: drop
    publishLocation: 'pipeline'